apiVersion: ray.io/v1
kind: RayService
metadata:
  name: $RAY_SERVICE_NAME
  namespace: $RAY_NAMESPACE
spec:
  serviceUnhealthySecondThreshold: 300
  deploymentUnhealthySecondThreshold: 300
  serveConfigV2: |
    applications:
    - name: mnist_classifier
      import_path: simple_serving:MNISTClassifier
      route_prefix: /mnist
      runtime_env:
        env_vars:
          RAY_CLUSTER_NAME: $RAY_CLUSTER_NAME
  rayClusterConfig:
    rayVersion: '2.8.0'
    headGroupSpec:
      replicas: 1
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: '0'
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.8.0
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 1
                memory: 1Gi
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
    workerGroupSpecs:
    - replicas: 2
      minReplicas: 1
      maxReplicas: 5
      groupName: small-group
      rayStartParams:
        num-cpus: '2'
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.8.0
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh","-c","ray stop"]
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 1
                memory: 1Gi
